require("plugins.setup")
require("plugins.default")
require("plugins.persistent_undo")

require("plugins.lualine")
require("plugins.nerdtree")
require("plugins.bufexplorer")
require("plugins.comment")
require("plugins.telescope")
require("plugins.nvim-treesitter")
require("plugins.gitsigns")
require("plugins.nvim-cmp")
require("plugins.nuuid")
require("plugins.vim-go")

require("plugins.null-ls")
require("plugins.prettier")
require("plugins.trouble")
